version: "3.8"
services:
  backend:
    build: ./IntelliSpendAI
    ports:
      - "8000:8000"
    env_file:
      - ./IntelliSpendAI/.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: intellidb
      POSTGRES_USER: intellidb
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 